class Solution{

    reverseWord(userInput){

        let result = '' // final reversed string will be stored here
        let convertedToArray = userInput.split(' ') // split string into words (may include empty strings for multiple spaces)

        for(let i = convertedToArray.length - 1; i >= 0; i--){

            // Removing extra spaces between the words (skipping empty strings generated by split)
            if(convertedToArray[i] === '') continue;

            // add current valid word to result
            result += `${convertedToArray[i]}`

            // Excluding last space form the resultant string:
            // add space only if there are still elements left to process
            if(i > 0){

                result += ` `
            }
        }

        return result // return final reversed sentence
    }
}

let input = ''

process.stdin.on('data', data => {
    input += data // accumulate input from stdin
})

process.stdin.on('end', () => {

    const enteredString = input.trim() // remove leading and trailing spaces

    if(enteredString.length > 1){

        console.log(`Entered String: ${enteredString}`)

        // call function and print reversed word string
        console.log(`Reversed words string: ${new Solution().reverseWord(enteredString)}`)
        return
    }

    console.log(`Cannot process empty string`)
    return
})